=== niclasdumesnil/marvelsdb_fanmade_data/schema/card_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"additionalProperties": true,
	"dependencies": {
		"name": [
			"faction_code",
			"type_code"
		]
	},
	"description": "JSON Schema for a Marvel Champions card — derived from Card.orm.yml",
	"properties": {
		"alt_art": {
			"type": "boolean"
		},
		"attack": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"attack_cost": {
			"minimum": 0,
			"type": "integer"
		},
		"attack_star": {
			"type": "boolean"
		},
		"back_flavor": {
			"minLength": 1,
			"type": "string"
		},
		"back_link": {
			"minLength": 1,
			"type": "string"
		},
		"back_name": {
			"minLength": 1,
			"type": "string"
		},
		"back_text": {
			"minLength": 1,
			"type": "string"
		},
		"base_threat": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"base_threat_fixed": {
			"type": "boolean"
		},
		"base_threat_per_group": {
			"type": "boolean"
		},
		"base_threat_star": {
			"type": "boolean"
		},
		"boost": {
			"minimum": 1,
			"type": "integer"
		},
		"boost_star": {
			"type": "boolean"
		},
		"code": {
			"pattern": "^[0-9]{5,6}[a-z]?$",
			"type": "string"
		},
		"cost": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"cost_per_hero": {
			"type": "boolean"
		},
		"creator": {
			"minLength": 1,
			"type": "string"
		},
		"deck_limit": {
			"minimum": 1,
			"type": "integer"
		},
		"deck_options": {
			"items": {
				"properties": {
					"faction": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"limit": {
						"minimum": 1,
						"type": "integer"
					},
					"multi_aspect": {
						"type": "boolean"
					},
					"name_limit": {
						"minimum": 1,
						"type": "integer"
					},
					"per_faction": {
						"type": "boolean"
					},
					"resource": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"trait": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"type": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"use_deck_limit": {
						"type": "boolean"
					}
				},
				"type": "object"
			},
			"minItems": 1,
			"type": "array"
		},
		"deck_requirements": {
			"items": {
				"properties": {
					"aspects": {
						"minimum": 1,
						"type": "integer"
					},
					"limit": {
						"minimum": 1,
						"type": "integer"
					}
				},
				"type": "object"
			},
			"minItems": 1,
			"type": "array"
		},
		"defense": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"defense_star": {
			"type": "boolean"
		},
		"double_sided": {
			"type": "boolean"
		},
		"duplicate_of": {
			"pattern": "^[0-9a-z]{5}[0-9a-z]?$",
			"type": "string"
		},
		"errata": {
			"minLength": 1,
			"type": "string"
		},
		"escalation_threat": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"escalation_threat_fixed": {
			"type": "boolean"
		},
		"escalation_threat_star": {
			"type": "boolean"
		},
		"expansions_needed": {
			"minLength": 1,
			"type": "string"
		},
		"faction2_code": {
			"minLength": 1,
			"type": "string"
		},
		"faction_code": {
			"minLength": 1,
			"type": "string"
		},
		"flavor": {
			"minLength": 0,
			"type": "string"
		},
		"hand_size": {
			"minimum": 1,
			"type": "integer"
		},
		"health": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"health_per_group": {
			"type": "boolean"
		},
		"health_per_hero": {
			"type": "boolean"
		},
		"health_star": {
			"type": "boolean"
		},
		"hidden": {
			"type": "boolean"
		},
		"illustrator": {
			"pattern": ".*",
			"type": "string"
		},
		"is_unique": {
			"oneOf": [
				{
					"type": "boolean"
				},
				{
					"type": "null"
				}
			]
		},
		"meta": {
			"type": "object"
		},
		"multiverse_of": {
			"pattern": "^[0-9]{5,6}[a-z]?$",
			"type": "string"
		},
		"name": {
			"minLength": 1,
			"type": "string"
		},
		"octgn_id": {
			"minLength": 1,
			"type": "string"
		},
		"pack_code": {
			"maxLength": 255,
			"minLength": 2,
			"type": "string"
		},
		"permanent": {
			"type": "boolean"
		},
		"position": {
			"minimum": 1,
			"type": "integer"
		},
		"quantity": {
			"minimum": 1,
			"type": "integer"
		},
		"recover": {
			"minimum": 0,
			"type": "integer"
		},
		"recover_star": {
			"type": "boolean"
		},
		"resource_energy": {
			"minimum": 0,
			"type": "integer"
		},
		"resource_mental": {
			"minimum": 0,
			"type": "integer"
		},
		"resource_physical": {
			"minimum": 0,
			"type": "integer"
		},
		"resource_wild": {
			"minimum": 0,
			"type": "integer"
		},
		"restrictions": {
			"minLength": 1,
			"type": "string"
		},
		"scheme": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"scheme_acceleration": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_amplify": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_crisis": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_hazard": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_star": {
			"type": "boolean"
		},
		"set_code": {
			"minLength": 1,
			"type": "string"
		},
		"set_position": {
			"minimum": 1,
			"type": "integer"
		},
		"stage": {
			"minLength": 1,
			"type": "string"
		},
		"subname": {
			"minLength": 1,
			"type": "string"
		},
		"text": {
			"minLength": 1,
			"type": "string"
		},
		"threat": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"threat_fixed": {
			"type": "boolean"
		},
		"threat_per_group": {
			"type": "boolean"
		},
		"threat_star": {
			"type": "boolean"
		},
		"thwart": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"thwart_cost": {
			"minimum": 0,
			"type": "integer"
		},
		"thwart_star": {
			"type": "boolean"
		},
		"traits": {
			"minLength": 0,
			"type": "string"
		},
		"type_code": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"code",
		"pack_code",
		"position",
		"quantity"
	],
	"type": "object"
}

=== niclasdumesnil/marvelsdb_fanmade_data/pack/ncrawler_encounter.json
[
	{
		"boost": 2,
		"code": "48026",
		"faction_code": "encounter",
		"illustrator": "Bruno Frenda",
		"name": "Crisis of Faith",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048026",
		"pack_code": "ncrawler",
		"position": 26,
		"quantity": 1,
		"set_code": "nightcrawler",
		"text": "<b><i>Give to the Kurt Wagner player.</i></b>\nYou may flip to alter-ego form. Choose:\n• Exhaust Kurt Wagner → remove Crisis of Faith from the game.\n• Discard each [[Attack]] and [[Defense]] event from your hand. Discard this obligation.",
		"type_code": "obligation"
	},
	{
		"attack": 3,
		"boost_star": true,
		"code": "48027",
		"faction_code": "encounter",
		"health": 3,
		"is_unique": true,
		"name": "Azazel",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048027",
		"pack_code": "ncrawler",
		"position": 27,
		"quantity": 1,
		"scheme": 2,
		"set_code": "nightcrawler_nemesis",
		"set_position": 1,
		"text": "Quickstrike.\nAzazel cannot have upgrades attached.\n<hr />\n[star] <b>Boost</b>: Deal Azazel to the Kurt Wagner player as a facedown encounter card.",
		"traits": "Elite. Neyaphem.",
		"type_code": "minion"
	},
	{
		"base_threat": 5,
		"base_threat_fixed": true,
		"boost": 3,
		"code": "48028",
		"faction_code": "encounter",
		"flavor": "\"All of this could be yours, if you'd only join me!\"—Azazel",
		"illustrator": "Allie Preswick",
		"name": "Brimstone Dimension",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048028",
		"pack_code": "ncrawler",
		"position": 28,
		"quantity": 1,
		"set_code": "nightcrawler_nemesis",
		"set_position": 2,
		"text": "<b>When Defeated</b>: The player who defeated this scheme finds Azazel and deals him to themself as a facedown encounter card.",
		"type_code": "side_scheme"
	},
	{
		"attack": 1,
		"attack_star": true,
		"boost": 2,
		"code": "48029",
		"faction_code": "encounter",
		"name": "Azazel's Sword",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048029",
		"pack_code": "ncrawler",
		"position": 29,
		"quantity": 1,
		"set_code": "nightcrawler_nemesis",
		"set_position": 3,
		"text": "Attach to Azazel. Otherwise, attach to the villain.\n[star] Attached enemy's attacks gain piercing.\n<b>Hero Response</b>: After attached enemy attacks you, discard 1 random card from your hand → discard this card.",
		"traits": "Weapon.",
		"type_code": "attachment"
	},
	{
		"boost": 1,
		"code": "48030",
		"faction_code": "encounter",
		"flavor": "Azazel delights in frustrating his opponents by teleporting in and out of combat.",
		"name": "Brimstone Strike",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048030",
		"pack_code": "ncrawler",
		"position": 30,
		"quantity": 2,
		"set_code": "nightcrawler_nemesis",
		"set_position": 4,
		"text": "<b>When Revealed (Alter-Ego)</b>: Find Azazel and reveal him. He schemes.\n<b>When Revealed (Hero)</b>: Find Azazel and reveal him.",
		"type_code": "treachery"
	},
	{
		"base_threat": 2,
		"base_threat_fixed": true,
		"boost": 2,
		"code": "48033",
		"faction_code": "encounter",
		"name": "The Crazy Gang",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048033",
		"pack_code": "ncrawler",
		"position": 33,
		"quantity": 1,
		"scheme_acceleration": 1,
		"set_code": "crazy_gang",
		"set_position": 1,
		"text": "<b>Forced Response</b>: After a non-[[Elite]] minion schemes against a player, deal that minion to that player as a facedown encounter card. Then, if there is more than 1 player in the game, pass that facedown encounter card to the next player.",
		"type_code": "side_scheme"
	},
	{
		"attack": 1,
		"boost": 3,
		"code": "48034",
		"faction_code": "encounter",
		"flavor": "\"Off with his head!\"",
		"health": 4,
		"is_unique": true,
		"name": "Queen of Hearts",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048034",
		"pack_code": "ncrawler",
		"position": 34,
		"quantity": 1,
		"scheme": 0,
		"set_code": "crazy_gang",
		"set_position": 2,
		"text": "<b>When Revealed</b>: Search the encounter deck and discard pile for The Crazy Gang side scheme and reveal it. If it is already in play, deal yourself a facedown encounter card. <i>(Shuffle.)</i>",
		"traits": "Criminal. Queen.",
		"type_code": "minion"
	},
	{
		"attack": 1,
		"boost": 1,
		"code": "48035",
		"faction_code": "encounter",
		"flavor": "\"I'll kick you in the face with fun!\"",
		"health": 5,
		"is_unique": true,
		"name": "Jester",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048035",
		"pack_code": "ncrawler",
		"position": 35,
		"quantity": 1,
		"scheme": 0,
		"set_code": "crazy_gang",
		"set_position": 3,
		"text": "<b>When Revealed</b>: You are confused. If you were already confused, discard a support you control.",
		"traits": "Criminal.",
		"type_code": "minion"
	},
	{
		"attack": 2,
		"boost": 2,
		"code": "48036",
		"faction_code": "encounter",
		"flavor": "The Queen of Hearts keeps him busy with her catchphrase.",
		"health": 4,
		"is_unique": true,
		"name": "Executioner",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048036",
		"pack_code": "ncrawler",
		"position": 36,
		"quantity": 1,
		"scheme": 0,
		"set_code": "crazy_gang",
		"set_position": 4,
		"text": "<b>When Revealed</b>: Executioner attacks the friendly character with the fewest remaining hit points. If this attack defeats an ally, remove that ally from the game.",
		"traits": "Criminal.",
		"type_code": "minion"
	},
	{
		"attack": 2,
		"boost": 1,
		"code": "48037",
		"errata": "Removed the star icon (★) from the boost field. (RRG)",
		"faction_code": "encounter",
		"flavor": "\"Hyuk hyuk hyuk!\"",
		"health": 6,
		"is_unique": true,
		"name": "Tweedledope",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048037",
		"pack_code": "ncrawler",
		"position": 37,
		"quantity": 1,
		"scheme": 0,
		"set_code": "crazy_gang",
		"set_position": 5,
		"text": "<b>When Revealed</b>: You are stunned. If you were already stunned, discard an upgrade you control.",
		"traits": "Brute. Criminal.",
		"type_code": "minion"
	},
	{
		"boost": 1,
		"code": "48038",
		"faction_code": "encounter",
		"flavor": "It's basically all she ever says.",
		"name": "\"Off with His Head!\"",
		"octgn_id": "65f91d01-99db-4c7e-814f-28ddf0048038",
		"pack_code": "ncrawler",
		"position": 38,
		"quantity": 1,
		"set_code": "crazy_gang",
		"set_position": 6,
		"text": "<b>When Revealed</b>: Each minion activates against the player it is engaged with. If no minion activates this way, discard cards from the top of the encounter deck until a minion is discarded and reveal that minion.",
		"type_code": "treachery"
	}
]

=== niclasdumesnil/marvelsdb_fanmade_data/pack/old_man_logan_by_nugget.json
[
    {
        "code": "205601b",
        "faction_code": "hero",
        "hand_size": 6,
        "health": 12,
        "hidden": true,
        "is_unique": true,
        "name": "James Howlett",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056001",
        "pack_code": "old_man_logan_by_nugget",
        "position": 1,
        "quantity": 1,
        "recover": 4,
        "set_code": "old_man_logan_by_nugget",
        "text": "<b>Setup</b>: Search your deck, hand and discard pile for Wolverine's Claws and put it into play under your control.\n<i>Healing Factor</i> — <b>Action</b>: Remove 1 wound counter from the Old and Tired upgrade. (Limit once per round.)",
        "traits": "Mutant.",
        "type_code": "alter_ego"
    },
    {
        "attack": 2,
        "back_link": "205601b",
        "code": "205601a",
        "defense": 1,
        "errata": "Traits have been changed from \"[[Mutant]]. [[X-Man]]\" to \"[[X-Men]]\" (MC4DB)",
        "faction_code": "hero",
        "flavor": "\"Every time I start to think things won't go bad.\"",
        "hand_size": 5,
        "health": 12,
        "is_unique": true,
        "meta": {
            "colors": [
                "#645866",
                "#6f3d24",
                "#371b05",
                "#95a5a6"
            ],
            "offset": "-35px -33px"
        },
        "name": "Old Man Logan",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056001",
        "pack_code": "old_man_logan_by_nugget",
        "position": 1,
        "quantity": 1,
        "set_code": "old_man_logan_by_nugget",
        "text": "<i>Berserker</i> — <b>Action</b>: Place 1 wound counter on the Old and Tired upgrade. Old Man Logan gets +1 THW, +1 ATK and +1 DEF until the end of the round. (Limit once per round.)",
        "thwart": 1,
        "traits": "X-Men.",
        "type_code": "hero"
    },
    {
        "code": "205602",
        "cost": null,
        "deck_limit": 1,
        "faction_code": "hero",
        "name": "Old and Tired",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056002",
        "pack_code": "old_man_logan_by_nugget",
        "permanent": true,
        "position": 2,
        "quantity": 1,
        "set_code": "old_man_logan_by_nugget",
        "set_position": 1,
        "text": "Permanent. Setup.\nYou get -1 hit point for each wound counter here.\nWhile there are 6 or more wound counters here, you get +1 hand size.",
        "traits": "Condition.",
        "type_code": "upgrade"
    },
    {
        "code": "205603",
        "cost": 2,
        "deck_limit": 1,
        "faction_code": "hero",
        "is_unique": true,
        "name": "Wolverine's Claws",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056003",
        "pack_code": "old_man_logan_by_nugget",
        "position": 3,
        "quantity": 1,
        "resource_physical": 1,
        "set_code": "old_man_logan_by_nugget",
        "set_position": 2,
        "text": "<b>Interrupt</b>: When you attack, exhaust Wolverine's Claws → increase the damage that attack deals by 1 for each wound counter on Old and Tired (max 3 increase in damage). This attack gains piercing. Place 1 wound counter on Old and Tired.",
        "traits": "Weapon. Superpower.",
        "type_code": "upgrade"
    },
    {
        "code": "205604",
        "cost": 0,
        "deck_limit": 2,
        "faction_code": "hero",
        "flavor": "\"I let myself become chaos. Madness. Death.\" — Old Man Logan",
        "name": "Blind Rage",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056004",
        "pack_code": "old_man_logan_by_nugget",
        "position": 4,
        "quantity": 2,
        "resource_physical": 1,
        "set_code": "old_man_logan_by_nugget",
        "set_position": 3,
        "text": "<b>Hero Resource</b>: Exhaust Blind Rage → Place 1 wound counter on Old and Tired. Generate a [wild] resource.",
        "traits": "Condition.",
        "type_code": "upgrade"
    },
    {
        "code": "205605",
        "cost": 2,
        "deck_limit": 1,
        "faction_code": "hero",
        "name": "Adamantium Skeleton",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056005",
        "pack_code": "old_man_logan_by_nugget",
        "position": 5,
        "quantity": 1,
        "resource_energy": 1,
        "set_code": "old_man_logan_by_nugget",
        "set_position": 5,
        "text": "Old Man Logan gets +1 DEF.\n<b>Interrupt</b>: When a wound counter would be placed on Old and Tired, exhaust Adamantium Skeleton instead.",
        "traits": "Armor.",
        "type_code": "upgrade"
    },
    {
        "code": "205606",
        "cost": 2,
        "deck_limit": 1,
        "faction_code": "hero",
        "flavor": "\"This is what old is. Confusion, aches and pains.\" — Old Man Logan",
        "name": "Enhanced Healing Factor",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056006",
        "pack_code": "old_man_logan_by_nugget",
        "position": 6,
        "quantity": 1,
        "resource_energy": 1,
        "set_code": "old_man_logan_by_nugget",
        "set_position": 6,
        "text": "<b>Interrupt</b>: When you would be defeated, remove each wound counter from Old and Tired instead. Then, discard Enhanced Healing Factor.",
        "traits": "Preparation. Superpower.",
        "type_code": "upgrade"
    },
    {
        "attack": 2,
        "attack_cost": 1,
        "code": "205607",
        "cost": 3,
        "deck_limit": 1,
        "faction_code": "hero",
        "health": 3,
        "is_unique": true,
        "name": "Old Man Hawkeye",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056007",
        "pack_code": "old_man_logan_by_nugget",
        "position": 7,
        "quantity": 1,
        "resource_wild": 1,
        "set_code": "old_man_logan_by_nugget",
        "set_position": 7,
        "text": "Old Man Hawkeye enters play with 2 arrow counters on him.\n<b>Response</b>: After a minion engages you, remove 1 arrow counter from Old Man Hawkeye → deal 4 damage to that minion.",
        "thwart": 2,
        "thwart_cost": 1,
        "traits": "Avenger.",
        "type_code": "ally"
    },
    {
        "code": "205608",
        "cost": 1,
        "deck_limit": 2,
        "faction_code": "hero",
        "flavor": "SNIKT!",
        "name": "Savage Stab",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056008",
        "pack_code": "old_man_logan_by_nugget",
        "position": 8,
        "quantity": 2,
        "resource_physical": 1,
        "set_code": "old_man_logan_by_nugget",
        "set_position": 8,
        "text": "<b>Hero Action</b> <i>(attack)</i>: Place 1 wound counter on Old and Tired. Deal 3 damage to an enemy. If you paid for this card using a [physical] resource, ready Wolverine's Claws.",
        "traits": "Attack.",
        "type_code": "event"
    },
    {
        "code": "205609",
        "cost": 0,
        "deck_limit": 2,
        "faction_code": "hero",
        "name": "Unfazed",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056010",
        "pack_code": "old_man_logan_by_nugget",
        "position": 10,
        "quantity": 2,
        "resource_energy": 1,
        "set_code": "old_man_logan_by_nugget",
        "set_position": 10,
        "text": "<b>Interrupt</b>: When you would take any amount of damage from an attack, prevent 1 of that damage for each wound counter on Old and Tired. Place 1 wound counter on Old and Tired.",
        "traits": "Defense.",
        "type_code": "event"
    },
    {
        "code": "205610",
        "cost": 3,
        "deck_limit": 2,
        "faction_code": "hero",
        "name": "Vicious Animal",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056012",
        "pack_code": "old_man_logan_by_nugget",
        "position": 12,
        "quantity": 2,
        "resource_mental": 1,
        "set_code": "old_man_logan_by_nugget",
        "set_position": 12,
        "text": "<b>Hero Action</b> <i>(attack)</i>: Deal 2 damage to an enemy for each wound counter on Old and Tired (max 8 damage). You may divide the damage dealt by this attack among enemies as you choose. If you paid for this card using a [physical] resource, you may place a wound counter on Old and Tired.",
        "traits": "Attack.",
        "type_code": "event"
    },
    {
        "code": "205611",
        "cost": 2,
        "deck_limit": 2,
        "faction_code": "hero",
        "name": "Skilled Tracker",
        "octgn_id": "85ef87e7-7618-4420-b85f-fdf2bd056014",
        "pack_code": "old_man_logan_by_nugget",
        "position": 14,
        "quantity": 2,
        "resource_mental": 1,
        "set_code": "old_man_logan_by_nugget",
        "set_position": 14,
        "text": "<b>Action</b> <i>(thwart)</i>: Remove 1 threat from a scheme for each wound counter on Old and Tired (max 4 threat). If you paid for this card using a [mental] resource, you may remove a wound counter from Old and Tired.",
        "traits": "Skill. Thwart.",
        "type_code": "event"
    }
]

=== niclasdumesnil/marvelsdb_fanmade_data/pack/blink_by_kajislav_encounter.json
[
    {
        "boost": 2,
        "code": "201017",
        "faction_code": "encounter",
        "name": "Stranger in This Reality",
        "octgn_id": "381bd788-111a-5f4f-a3eb-bcb150000017",
        "pack_code": "blink_by_kajislav",
        "position": 10,
        "quantity": 1,
        "set_code": "blink_by_kajislav",
        "text": "You may flip to alter-ego form. Choose:\nExhaust Clarice Ferguson → remove Stranger in This Reality from the game.\nDiscard each [[portal]] upgrade from play. If no [[portal]] upgrade was discarded this way, this card gains surge. Discard this obligation.",
        "type_code": "obligation"
    },
    {
        "attack": 0,
        "attack_star": true,
        "boost": 2,
        "code": "201018",
        "faction_code": "encounter",
        "health": 1,
        "is_unique": true,
        "name": "Timebroker",
        "octgn_id": "381bd788-111a-5f4f-a3eb-bcb150000018",
        "pack_code": "blink_by_kajislav",
        "position": 11,
        "quantity": 1,
        "scheme": 2,
        "scheme_star": true,
        "set_code": "blink_by_kajislav_nemesis",
        "set_position": 1,
        "text": "Timebroker cannot take damage. [star] <b>Forced Response</b>: After Timebroker activates, place 2 threat on the Damaged Reality side scheme.<b>\nForced Response</b>: After Timebroker enters play, find the Damaged Reality side scheme and reveal it.\n<i>(Blink's nemesis minion.)\n</i>",
        "traits": "Illusion.",
        "type_code": "minion"
    },
    {
        "base_threat": 2,
        "base_threat_fixed": true,
        "boost": 2,
        "code": "201019",
        "faction_code": "encounter",
        "name": "Damaged Reality",
        "octgn_id": "381bd788-111a-5f4f-a3eb-bcb150000019",
        "pack_code": "blink_by_kajislav",
        "position": 12,
        "quantity": 1,
        "set_code": "blink_by_kajislav_nemesis",
        "set_position": 2,
        "text": "<i>Timebreakers had accidentally damaged many realities across the Multiverse and tricked heroes into fixing their mistake.</i>\n<b>When Revealed</b>: Place 1 additional threat here for each upgrade in play. Then, discard an upgrade you control.\n<b>When Defeated</b>: Discard Timebroker.\n[crisis]\n [star] <b>Boost</b>: Reveal this card.",
        "type_code": "side_scheme"
    },
    {
        "boost": 1,
        "code": "201020",
        "faction_code": "encounter",
        "name": "Timebreakers",
        "octgn_id": "381bd788-111a-5f4f-a3eb-bcb150000020",
        "pack_code": "blink_by_kajislav",
        "position": 13,
        "quantity": 3,
        "set_code": "blink_by_kajislav_nemesis",
        "set_position": 3,
        "text": "<b>When Revealed</b>: Search the encounter deck and discard pile for Timebroker and reveal him. <i>(Shuffle.)</i> If Timebroker does not enter play this way, this card gains surge.\n<i>\"Must we really sacrifice a reality just to teach them a lesson?\" —Timebreakers </i>",
        "type_code": "treachery"
    }
]

=== niclasdumesnil/marvelsdb_fanmade_data/pack/venompool_by_cptscorp_encounter.json
[
	{
		"boost": 2,
		"code": "206211",
		"faction_code": "encounter",
		"name": "One Too Many Voices",
		"octgn_id": "0c714380-7fb9-4a28-9c0f-872b09062011",
		"pack_code": "venompool_by_cptscorp",
		"position": 11,
		"quantity": 1,
		"set_code": "venompool_by_cptscorp",
		"text": "You must flip to alter-ego form. Choose:\nExhaust Wade Wilson → remove One Too Many Voices from the game.\nDiscard Klyntar Suit. If Klyntar Suit was not discarded this way, this card gains surge. Discard this obligation.",
		"type_code": "obligation"
	},
	{
		"base_threat": 2,
		"boost": 2,
		"boost_star": true,
		"code": "206212",
		"faction_code": "encounter",
		"name": "Shocking Entrance",
		"octgn_id": "0c714380-7fb9-4a28-9c0f-872b09062012",
		"pack_code": "venompool_by_cptscorp",
		"position": 12,
		"quantity": 1,
		"set_code": "venompool_by_cptscorp_nemesis",
		"set_position": 1,
		"text": "<i>\"Surrender the Klyntar.\" -Killer Thrill</i><b>\nWhen Revealed</b>: Deal 3 indirect damage to the first player.\n[hazard]\n<b>\t\t Boost</b>: Deal 1 indirect damage to the first player.",
		"type_code": "side_scheme"
	},
	{
		"attack": 2,
		"attack_star": true,
		"boost": 2,
		"code": "206213",
		"faction_code": "encounter",
		"health": 5,
		"is_unique": true,
		"name": "Killer Thrill",
		"octgn_id": "0c714380-7fb9-4a28-9c0f-872b09062013",
		"pack_code": "venompool_by_cptscorp",
		"position": 13,
		"quantity": 1,
		"scheme": 2,
		"set_code": "venompool_by_cptscorp_nemesis",
		"set_position": 2,
		"text": "[star] Killer Thrill gets +1 ATK for each adrenaline counter on her.\n<b>Forced Interrupt</b>: When the player phase ends, put 1 adrenaline counter on Killer Thrill. Then, if there are 2 or more adrenaline counters on her, remove them all and she activates.\n<i>(Venompool's nemesis minion.)</i>",
		"traits": "Alien. Bounty Hunter.",
		"type_code": "minion"
	},
	{
		"attack": 1,
		"attack_star": true,
		"boost": 1,
		"boost_star": true,
		"code": "206214",
		"faction_code": "encounter",
		"health": 2,
		"is_unique": true,
		"name": "Coldwar",
		"octgn_id": "0c714380-7fb9-4a28-9c0f-872b09062014",
		"pack_code": "venompool_by_cptscorp",
		"position": 14,
		"quantity": 1,
		"scheme": 1,
		"set_code": "venompool_by_cptscorp_nemesis",
		"set_position": 3,
		"text": "Quickstrike. <i>(After this minion engages your hero, it attacks you.)</i> [star] While Killer Thrill is in play, Coldwar gets +1 ATK.\n<b> Boost</b>: After this activation, deal this card to yourself as a facedown encounter card.",
		"traits": "Alien. Bounty Hunter.",
		"type_code": "minion"
	},
	{
		"attack": 1,
		"boost": 1,
		"boost_star": true,
		"code": "206215",
		"faction_code": "encounter",
		"health": 2,
		"is_unique": true,
		"name": "Guzz",
		"octgn_id": "0c714380-7fb9-4a28-9c0f-872b09062015",
		"pack_code": "venompool_by_cptscorp",
		"position": 15,
		"quantity": 1,
		"scheme": 1,
		"scheme_star": true,
		"set_code": "venompool_by_cptscorp_nemesis",
		"set_position": 4,
		"text": "Plotting. <i>(After this minion engages you, it schemes.)</i> [star] While Killer Thrill is in play, Guzz gets +1 SCH.\n<b> Boost</b>: After this activation, deal this card to yourself as a facedown encounter card.",
		"traits": "Alien. Bounty Hunter.",
		"type_code": "minion"
	},
	{
		"boost": 3,
		"code": "206216",
		"faction_code": "encounter",
		"name": "Psyche Warp",
		"octgn_id": "0c714380-7fb9-4a28-9c0f-872b09062016",
		"pack_code": "venompool_by_cptscorp",
		"position": 16,
		"quantity": 1,
		"set_code": "venompool_by_cptscorp_nemesis",
		"set_position": 5,
		"text": "<b>When Revealed</b>: You take X damage where X is equal to the ATK of the ally with the highest printed ATK. Discard that ally. If no damage was taken this way, this card gains surge.",
		"type_code": "treachery"
	}
]
